baseURL = "http://b-nadji.com/"
languageCode = "fr-fr"
title = "Mon Portfolio"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Nadjidine BOINALI"
    description = "Portfolio S10 IL Janvier 2021 con√ßu avec Hugo"
    githubUsername = "#"
    accent = "#A91818"
    showBorder = true
    backgroundColor = "#F0EEEB"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

# Permit raw html
[markup.goldmark.renderer]
    unsafe= true

[[menu.main]]
    url = "/"
    name = "Accueil"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/projets/"
    name = "Projets"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:n.boinali@intech-sud.fr"
    name = "envelope-o"
    weight = 1


[[menu.icon]]
    url = "https://www.linkedin.com/in/nadjidine-b-834a65164/"
    name = "linkedin"
    weight = 2
